version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    # volumes:
    #   - "./conf.d:/etc/mysql/conf.d:ro"

  java_application:
    depends_on:
      - mysql
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    privileged: true
